# Generated by Django 4.2.4 on 2023-09-01 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=20)),
                ("pub_date", models.DateTimeField()),
                ("intro", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("link", models.CharField(max_length=100)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("新浪数码", "Shuma"),
                            ("新浪科技", "Keji"),
                            ("IT之家", "It"),
                            ("快科技", "Kuai"),
                            ("太平洋电脑网", "Pacific"),
                            ("中关村在线", "Zx"),
                            ("中国家电网", "Jd"),
                            ("CNMO", "Cnmo"),
                            ("市场资讯", "Market"),
                            ("媒体滚动", "Run"),
                            ("新浪科技综合", "Kjzh"),
                            ("澎湃新闻", "Pp"),
                            ("财联社", "Cl"),
                            ("快科技2018", "K"),
                            ("界面新闻", "Jm"),
                            ("其他", "Other"),
                        ],
                        default="其他",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=10)),
                ("comment_content", models.CharField(max_length=1000)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="news.news"
                    ),
                ),
            ],
        ),
    ]
