# Generated by Django 4.2.4 on 2023-09-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
