# Generated by Django 4.2.4 on 2023-09-01 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_comment_create_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
