# Generated by Django 4.2.4 on 2023-09-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_alter_comment_create_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="hotness",
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
