# Generated by Django 4.2.4 on 2023-09-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_delete_image_news_imgs_num_alter_news_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="comment_num",
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
